### ISSUE TITLE
hw3

### ISSUE THREAD

**Issue by imgarylai** [clin366/cs571#2]
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/app/src/__init__.py", line 18, in <module>
    from .hw3 import NamedEntityRecognizer
  File "/app/src/hw3.py", line 26, in <module>
    from keras.layers import Conv2D, MaxPooling2D, Input, Dense, concatenate, Dropout, Activation, Flatten
ModuleNotFoundError: No module named 'keras'
```

**Comment by clin366** [comment]
hi, issue solved by updating requirements.txt, please re-run the code, thanks !

**Comment by imgarylai** [comment]
```
2019-05-02 16:09:36.088645: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/src/eval.py", line 13, in <module>
    score = named_entity_recognizer.evaluate(tst_data)
  File "/app/src/hw3.py", line 214, in evaluate
    preds = self.decode(data)
  File "/app/src/hw3.py", line 193, in decode
    padding_xs = self.padding_training(xs)
  File "/app/src/hw3.py", line 165, in padding_training
    train_xs = train_xs.reshape(train_xs.shape[0], train_xs.shape[1], train_xs.shape[2])
IndexError: tuple index out of range
Loaded model from disk
```

**Comment by clin366** [comment]
> ```
> 2019-05-02 16:09:36.088645: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/app/src/eval.py", line 13, in <module>
>     score = named_entity_recognizer.evaluate(tst_data)
>   File "/app/src/hw3.py", line 214, in evaluate
>     preds = self.decode(data)
>   File "/app/src/hw3.py", line 193, in decode
>     padding_xs = self.padding_training(xs)
>   File "/app/src/hw3.py", line 165, in padding_training
>     train_xs = train_xs.reshape(train_xs.shape[0], train_xs.shape[1], train_xs.shape[2])
> IndexError: tuple index out of range
> Loaded model from disk
> ```
Hi, is it because tst_data shape?  we don't have the annotation of tst_data, if replace tst_data with dev_data, there will be no mistake.

**Comment by imgarylai** [comment]
This homework must be tested on tst data. Otherwise, the score is useless.

**Comment by clin366** [comment]
> This homework must be tested on tst data. Otherwise, the score is useless.

I‘ve run the code successfully on the  aws docker, I'll check for this, and reply this issue very quickly, I suppose it's because the maximum length of tst data is longer than 113.

**Comment by clin366** [comment]
> > This homework must be tested on tst data. Otherwise, the score is useless.
> 
> I‘ve run the code successfully on the aws docker, I'll check for this, and reply this issue very quickly, I suppose it's because the maximum length of tst data is longer than 113.

Hi, every issue fixed and run successfully on AWS:
the result:
ubuntu@ip-172-31-47-252:~/cs571/hw3$ sudo docker run -v /home/ubuntu/cs571/hw3:/mnt:rw -e "RESOURCE=/mnt/res/" hw3
2019-05-02 18:11:06.927632: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loaded model from disk
0.0 17.76351833343506

Please update the correct 'conll03.eng.tst.tsv' and run this version. 

Thanks!

**Comment by imgarylai** [comment]
Your model name should be `hw3-model` no matter it's a file or directory. Please change it to the correct name
I also considered other files you uploaded here. That should not be an issue.

**Comment by clin366** [comment]
> Your model name should be `hw3-model` no matter it's a file or directory. Please change it to the correct name
> I also considered other files you uploaded here. That should not be an issue.

Thanks, I've changed the name to 'hw3-model' and updated the eavl.py, hw3.py. Did you successfully run through the codes? Did my result make sense? Sorry for my carelessness. 

Thanks,
Chen Lin

**Comment by imgarylai** [comment]
Yes, it is!
